#!/bin/sh

    echo "" > /usr/aprenderer/aprenderer.log
    printf "Starting APlayer UPNP: "
    chattr -i /etc/asound.conf
    grep -q "APrenderer" /etc/asound.conf || cat /etc/asound.ap > /etc/asound.conf
    sync
    grep -q USB /etc/output && sed -i -e 's/card 0/card 1/g' /etc/asound.conf
    sync    
    chattr +i /etc/asound.conf
    
    i=1
    while [ $i -lt 300 ]
    do
	echo "Number: $i"
	((i++))
	network=`ifconfig eth0 |grep "inet addr"`
	if [[ -n "$network"  ]]; then
	break
	fi
	sleep 1
    done

    MAC=`cat /sys/class/net/eth0/address`
    NAME=PURE_`sed -r 's/..:..:..:..:(..):(..)/\1\2/' /sys/class/net/eth0/address | tr 'a-z' 'A-Z'`
    sed -i -e "s/<mac>.*<\/mac>/<mac>$MAC<\/mac>/g" /usr/aprenderer/upnp/config.xml
    sed -i -e "s/<name>.*<\/name>/<name>$NAME<\/name>/g" /usr/aprenderer/upnp/config.xml
    /usr/aprenderer/upnp/squeeze2upnp -z -k -x /usr/aprenderer/upnp/config.xml
    cd /usr/aprenderer
    exec nice -n -15 ./ap2renderer 
    sync    
