#!/bin/sh


case "$1" in
    start)
    pidof networkaudiod && exit
    printf "Starting NAA: "
    chattr -i /etc/asound.conf
    if grep -q USB /etc/output; then
	# Enable USB Audio
	sed -i -e 's/card 0/card 1/g' /etc/asound.conf
    fi
    sync
    nice -n -15 /sbin/networkaudiod > /tmp/naa.log 2>&1 &
	;;
    stop)
    killall -9 networkaudiod
    ;;
    *)
	exit 1
esac
