#!/bin/sh


case "$1" in
    start)
    printf "Starting RoonBrige: "
    chattr -i /etc/asound.conf
    if grep -q USB /etc/output; then
	# Enable USB Audio
	sed -i -e 's/card 0/card 1/g' /etc/asound.conf
    fi
    sync
    start-stop-daemon --start --quiet --background --exec /opt/RoonReady/startroon.sh  \
	&& echo "OK" || echo "FAIL"
	;;
    stop)
    killall startroon.sh raat_app
    ;;
    *)
	exit 1
esac
