#!/bin/sh


case "$1" in
    start)
    printf "Starting Tidal Connect: "
    chattr -i /etc/asound.conf
    if grep -q USB /etc/output; then
	# Enable USB Audio
	sed -i -e 's/card 0/card 1/g' /etc/asound.conf
    fi
    sync

i=1
while [ $i -lt 300 ]
    do
    echo "Number: $i"
    ((i++))
    network=`ifconfig eth0 |grep "inet addr"`
    if [[ -n "$network"  ]]; then
    break
    fi
    sleep 1
done
    
    # Disabled IP for Great Russian Firewall :)
    iptables -A OUTPUT -p tcp -d 65.9.57.52 -j REJECT
    
    start-stop-daemon --start --quiet --background --exec /usr/bin/start_tc  \
	&& echo "OK" || echo "FAIL"
	;;
    stop)
	/usr/bin/stop_tc
	;;
    *)
	exit 1
esac







