#!/bin/sh


case "$1" in
    start)
    printf "Starting Tidal Connect: "
    chattr -i /etc/asound.conf
    if grep -q USB /etc/output; then
	# Enable USB Audio
	sed -i -e 's/card 0/card 1/g' /etc/asound.conf
    fi
    sync

    while [ $i -lt 300 ]
    do
    echo "Number: $i"
    ((i++))
    network=`ifconfig eth0 |grep "inet addr"`
    if [[ -n "$network"  ]]; then
    break
    fi
    sleep 1
    done

	ip addr add 52.85.115.21/32 dev eth0:1
	ip addr add 52.85.242.31/32 dev eth0:2
	ip addr add 52.85.115.61/32 dev eth0:3
    sleep 0.5
    start-stop-daemon --start --quiet --background --exec /usr/bin/start_tc  \
	&& echo "OK" || echo "FAIL"
	;;
    stop)
	/usr/bin/stop_tc
	ip addr del 52.85.115.21/32 dev eth0:1
	ip addr del 52.85.242.31/32 dev eth0:2
	ip addr del 52.85.115.61/32 dev eth0:3

    ;;
    *)
	exit 1
esac







