#!/bin/sh


case "$1" in
  start)
    cat /etc/random-seed >/dev/urandom
    /sbin/rndaddtoentcnt 1024

    echo 113 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio113/direction
    echo 1 > /sys/class/gpio/gpio113/value
    echo 51 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio51/direction
    echo 1 > /sys/class/gpio/gpio51/value

    test -f /etc/output || echo USB > /etc/output
    grep -q I2S /etc/output && /etc/rc.botic/S10mute start
    
    ;;
 *)
    exit 1
esac

