#!/bin/sh

        printf "Starting $NAME: "
	NAME=PURE_`sed -r 's/..:..:..:..:(..):(..)/\1\2/' /sys/class/net/eth0/address | tr 'a-z' 'A-Z'`
	sed -i "s/^friendlyname.*/friendlyname = $NAME/" /etc/upmpdcli.conf

exec  /usr/bin/upmpdcli -c /etc/upmpdcli.conf
